FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Groot:
      id: 3
      type: Groot

  Passive:
    transitions: 
      FixStand: LT + up.on_pressed | LT.on_pressed + up
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed | LT.on_pressed + B
      Groot: RB + X.on_pressed | RB.on_pressed + X
    kp: [
      100., 100., 100., 150., 40., 40.,
      100., 100., 100., 150., 40., 40.,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0, 0.25,0,0.97,0.15, 0,0,
        0, -0.25,0,0.97,-0.15, 0,0
      ]
    ]
  Groot:
    transitions: 
      Passive: LT + B.on_pressed | LT.on_pressed + B
    policy_dir: config/policy/groot
    arm_transition:
      duration_ms: 500
    zmq:
      port: 6002
      state_port: 6001
